"""fix_comment_self_reference

Revision ID: ae2771ad9c6a
Revises: 004
Create Date: 2025-12-05 17:14:06.752699

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '005'
down_revision = '004'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('comment_ibfk_2'), type_='foreignkey')
        batch_op.create_foreign_key('comment_ibfk_2', 'comment', ['parent_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint('comment_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('comment_ibfk_2'), 'comment', ['parent_id'], ['id'])

    # ### end Alembic commands ###
