"""create_comment_model

Revision ID: 83ac2c49cf5c
Revises: 001
Create Date: 2025-11-10 01:43:44.379510

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '83ac2c49cf5c'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('dataset_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('parent_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('content', mysql.VARCHAR(length=256), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('visible', mysql.TINYINT(display_width=1), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['data_set.id'], name=op.f('comment_ibfk_2')),
    sa.ForeignKeyConstraint(['parent_id'], ['comment.id'], name=op.f('comment_ibfk_3')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('comment_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment')
    # ### end Alembic commands ###
    # ### end Alembic commands ###